### ISSUE TITLE
Frankwatching 2018

### ISSUE THREAD

**Issue by dennisbuis** [stichtingjoomlanederland/media#1]
![full_1000x500](https://user-images.githubusercontent.com/3339738/35914317-239f8aaa-0c03-11e8-972d-1adc563876f8.jpg)
![intro_300x310](https://user-images.githubusercontent.com/3339738/35914318-23b5903e-0c03-11e8-819b-348805c736a9.jpg)
![logo_214x156](https://user-images.githubusercontent.com/3339738/35914319-23cdea30-0c03-11e8-9d7b-3287c41234cb.jpg)

**Comment by dennisbuis** [comment]
De Indesign bron bestanden...
[Intro_300x310 Folder.zip](https://github.com/stichtingsympathy/media/files/1702887/Intro_300x310.Folder.zip)
[Uploading logo_214x156 Folder.zip…]()
[Uploading Full_1000x500 Folder.zip…]()

**Comment by crommie** [comment]
Er is nog wel een dingetje: sinds vorig jaar schrijven we JoomlaDagen als JoomlaDagen, dus zonder uitroepteken en met hoofdletter D. Omdat we nu haast hebben laten we het ff zoals het nu is, maar voor komende uitingen moeten we er consequent in zijn (maar aangezien alles nu zo'n beetje een uitroepteken + kleine letter is, is dat juist wel weer consequent...)
